name: Build Static Node.js Container

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/build-static-node.yml'
      - 'staticnode/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-static-node.yml'
      - 'staticnode/**'

jobs:
  build:
    name: Build node.js
    runs-on: ${{ matrix.IMAGE.RUNNER }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        IMAGE:
          - {RUNNER: "ubuntu-latest", MANYLINUX_ARCH: "loongarch64"}
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - name: Set Node.js version
      run: |
        source ./staticnode/node-version.sh
        echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
        echo "NODE_SHA256SUM=$NODE_SHA256SUM" >> $GITHUB_ENV
        arch=loongarch64
        echo "NODE_ARCH=$arch" >> $GITHUB_ENV
    - name: Setup QEMU
      run: docker run --rm --privileged ghcr.io/loong64/qemu-user-static --reset -p yes
    - name: Build the Docker image
      run: |
        echo building node.js $NODE_VERSION
        docker build --tag ghcr.io/loong64/static-nodejs-$NODE_ARCH:$NODE_VERSION --build-arg VERSION=$NODE_VERSION --build-arg ARCH=loong64 --build-arg SHA256SUM=$NODE_SHA256SUM staticnode
    - name: Test static node.js on manylinux_2_38
      run: |
        cd staticnode
        docker build -f Dockerfile-test -t test-node --build-arg MANYLINUX_ARCH=${{ matrix.IMAGE.MANYLINUX_ARCH }} --build-arg CONTAINER_NAME=ghcr.io/loong64/static-nodejs-$NODE_ARCH:$NODE_VERSION .
        docker run test-node /staticnode/bin/node -e "console.log('hello world'); console.log(process.version)"
    - name: Login to docker
      run: 'docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" ghcr.io'
      env:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image
      run: docker push "ghcr.io/loong64/static-nodejs-${NODE_ARCH}:${NODE_VERSION}"
